#!/usr/bin/env bash
set -euo pipefail

##? action release

export FRE_HOME="$(cd "$(dirname "$0")/.." && pwd)"
source "${FRE_HOME}/scripts/install"

release() {

   TAR_DIR="${FRE_HOME}/target/tar"

   target="${1:-}"
   if [[ $target == *"osx"* ]]; then
      echoerr "OSX cross-compile is impossible. Fallbacking to cargo..."
      target=""
   fi

   cd "$FRE_HOME"

   rm -rf "${FRE_HOME}/target" 2> /dev/null || true

   if [ -n "$target" ]; then
      cargo install cross 2> /dev/null || true
      cross build --release --locked --target "$target"
      bin_folder="${target}/release"
   else
      cargo build --release --locked
      bin_folder="release"
   fi

   bin_path="${FRE_HOME}/target/${bin_folder}/fre"
   chmod +x "$bin_path"
   mkdir -p "$TAR_DIR" 2> /dev/null || true

   cp "$bin_path" "$TAR_DIR"

   cd "${FRE_HOME}/target/tar"
   tar -czf fre.tar.gz *

}

cmd="$1"
shift

case "$cmd" in
   "release") release "$@" ;;
esac
