#!/usr/bin/env bash
set -euo pipefail

export FRE_HOME="$(cd "$(dirname "$0")/.." && pwd)"

cd "$FRE_HOME"

./scripts/action release x86_64-unknown-linux-musl

docker run \
   -e HOMEBREW_NO_AUTO_UPDATE=1 \
   -e HOMEBREW_NO_INSTALL_CLEANUP=1 \
   -v "$(pwd):/fre" \
   -it 'bashell/alpine-bash' \
   bash -c 'apk add git; apk add curl; git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && yes | ln -s /fre/target/debug/fre /usr/local/bin/fre; source $HOME/.bashrc; bash'
