#!/usr/bin/env bash
set -euo pipefail

export FRE_HOME="$(cd "$(dirname "$0")/.." && pwd)"
source "${FRE_HOME}/scripts/install"

version="${1:-$(version_from_toml)}"
echo "version: $version..."
sleep 2

git tag -a "v${version}"
git push origin --tags
